


POST /api/v1/login HTTP/1.1
Host: localhost:8081
content-type: application/json

{
    "email": "thanhhung.code@gmail.com",
    "password": "admin123"
}

################################




POST /api/v1/login HTTP/1.1
Host: localhost:8081
content-type: application/json

{
    "email": "thanhhung.cod@gmail.com"
}

################################