GET http://localhost:8081/api/v1/users HTTP/1.1
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDlkZDI0MWU3MjhjMDBmNTI3ZmI0ZDUiLCJuYW1lIjoidGVzdCB0aOG7rSIsImVtYWlsIjoidGhhbmhodW5nLmNvZGVAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMS0wNS0xNFQwMToyODozMy4yMjJaIiwidXBkYXRlZEF0IjoiMjAyMS0wNS0xNFQwMToyODozMy4yMjJaIiwiYXV0aG9yaXphdGlvbiI6InVzZXIiLCJpYXQiOjE2MjA5NjEzMjcsImV4cCI6MTYyMTIyMDUyN30.J_P6VxrkjFkabkl1HAVo9hmW16q2OaBrQF19Cr29JkU
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
################################



GET http://localhost:8081/api/v1/users HTTP/1.1
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGEyMmE5ZTFmOTJiOTEwZmM4ZjQ3NTYiLCJuYW1lIjoidGVzdCB0aOG7rSIsImVtYWlsIjoidGhhbmhodW5nLmNvZGVAZ21haWwuY29tIiwiZ2VuZGVyIjoxLCJjcmVhdGVkQXQiOiIyMDIxLTA1LTE3VDA4OjM0OjM4LjU0MVoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA1LTE3VDA4OjM0OjM4LjU0MVoiLCJhdXRob3JpemF0aW9uIjoidXNlciIsImlhdCI6MTYyMTgzOTAwMywiZXhwIjoxNjIxODQyNjAzfQ.yBN7wA6k9AFMgiP6sVivqEVGzYifqwjWbNsSkqJLFkM
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
################################



GET http://localhost:8081/api/v1/users HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
################################